### PR TITLE
Add !8ball plugin

### PR DESCRIPTION
**Pull request by andrgorr**
Requested by @eudaldca , thought it was a cool project to start on python: tested the basics on PyCharm and it should work perfectly fine.

### CODE REVIEW

**Comment by eudaldca** [comment]
:+1:

**Comment by Plastix** [comment]
Just address the two comments made and squash your commits together if you can. Thanks for the help! Always open to more features.

**Comment by andrgorr** [comment]
@Plastix Done :smile: :8ball: 

I think we should keep the wiki link in the help though, as it can help players know what the whole 8ball thing is about in case we don't know. It's on the extended thing part, so it will only pop up when you do !help.

**Comment by Plastix** [comment]
I squashed your commits together and merged with 593941ec42918a389a348a5d35e8c5033bb34e73. Thanks! :+1:

**Pull request closed without merging**
